name: Publish Package Distribution

# Trigger only on tags like v1.2.3
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    # Only minimal permissions needed here
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pre-commit hooks
        run: uv run pre-commit run -a

      - name: Run tests
        run: uv run pytest tests

      - name: Upload distributions
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write                     # Enable OIDC token issuance [oai_citation_attribution:10‡GitHub Docs](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-pypi?utm_source=chatgpt.com)
      contents: read
      packages: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No username/password or API token needed: OIDC flows automatically [oai_citation_attribution:9‡GitHub](https://github.com/pypa/gh-action-pypi-publish?utm_source=chatgpt.com)
